model:
  params:
    resolution: 256
    in_channels: 3
    out_channels: 3
    z_channels: 256
    downsample_rate: 2
    num_res_blocks: 2
    num_input_channels: 3
    latent_channels: 256
    quantize_latent: true
    # add other required parameters here

    # Encoder settings
    encoder: 
      target: taming.models.vqgan.VQEncoder
      params:
        resolution: 256
        z_channels: 256

    # Decoder settings
    decoder:
      target: taming.models.vqgan.VQDecoder
      params:
        resolution: 256
        z_channels: 256

    # Post-quantization convolution layer
    post_quant_conv:
      target: taming.models.vqgan.Conv2d
      params:
        in_channels: 256
        out_channels: 256
        kernel_size: 3
        stride: 1
        padding: 1
